List:
A list is a built-in data type in Python. It's a collection of values that can be of any data type, including numbers, strings, other lists, and more. Lists are mutable, meaning you can modify their contents (add, remove, or change elements) after creation. Lists are quite flexible and versatile, but they might not be as efficient as specialized data structures like arrays for certain operations.


In [1]:
my_list = [1, 2, 3, 4, 5]


NumPy Array:
A NumPy array is a part of the NumPy library, which provides support for arrays and matrices. Arrays are homogeneous, meaning they store elements of the same data type. They are more memory-efficient and faster than lists for numerical computations, especially when dealing with large datasets. NumPy arrays also offer a wide range of mathematical operations and functions optimized for numerical calculations.

In [7]:
import numpy as np

my_array = np.array([1, 2, 3, 4, 5])


array([1, 2, 3, 4, 5])

In summary, the key differences between lists and NumPy arrays include their mutability, memory efficiency, and the availability of specialized numerical operations. If you're working with numerical data and require efficient computation, NumPy arrays are generally a better choice. If you need a collection of different data types or need to modify the contents frequently, lists might be more appropriate.







# Write a code to print the data type of each and every element of both the variables list_ and arra_list.


In [11]:
import numpy as np
my_list=[1,2,3,'three',5.6]
ny_array=np.array([1,2,3,4,5,6])
print("data type of elements of list are")
for item in my_list:
    print(type(item))
print("data type of elements of array are")
for item in my_array:
    print(type(item))



data type of elements of list are
<class 'int'>
<class 'int'>
<class 'int'>
<class 'str'>
<class 'float'>
data type of elements of array are
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [8]:
import numpy as np
num_array=np.array([[1,2,3],[4,5,6]])
shape=num_array.shape
print("the shape of the num_array is",shape)
size=num_array.size
print("the size of the num_arrayis ",size)

the shape of the num_array is (2, 3)
the size of the num_arrayis  6


# Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.


In [9]:
null_array=np.zeros([3,3])

In [10]:
null_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [14]:
identity_matrix=np.eye(5)

In [18]:
identity_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])